
[aliases]
l = ["log", "-r", "(trunk()..@)- | @"]
ll = ["log", "-r", "(trunk()..@):: | (trunk()..@)-"]
lr = ["log", "-r"]
cp = ["duplicate"]
sp = ["split"]
pl = ["parallelize"]
sync = ["rebase", "-s", "roots(trunk()..@)", "-d", "trunk()"]

wa = [
    'util',
    'exec',
    '--',
    'bash',
    '-c',
    'jj workspace add --name $0 $(jj workspace root).$0',
]

[user]
name = "Matt Cuento"
email = "cuentomr17@gmail.com"

[signing]
backend = "gpg"
key = "68F435624B13E3EA"
behavior = "own"

[templates]
log = '''
change_id.shortest(7) ++ " " ++
committer.timestamp().ago() ++ " " ++
if(self.contained_in("first_parent(@)"), label("git_head_label", "HEAD "), "") ++
if(conflict, label("conflict", "(conflict) "), "") ++
if(divergent, label("divergent", "(divergent) "), "") ++
separate(", ",
  self.remote_bookmarks().filter(|r| r.remote() == "origin").map(|r| label("bookmark", "✦" ++ r.name())),
  self.local_bookmarks().map(|r| label("bookmark", r.name())),
  self.tags().map(|r| label("bookmark", r.name())),
) ++
if(author.email() == "you@example.com", "", " " ++ author.email()) ++
"\n " ++
commit_id.shortest(6) ++ " " ++
if(conflict, label("conflict", "×× "), "") ++
if(divergent, label("divergent", "﹖ "), "") ++
if(empty,
  label("empty", "(empty) ") ++ description.first_line(),
  if(description.first_line(),
    description.first_line(),
    label("empty description placeholder", "(no description)")
  )
) ++
"\n"
'''

[merge-tools.vimdiff]
program = "nvim"

[merge-tools.diffconflicts]
program = "nvim"
merge-args = [
  "-c", "let g:jj_diffconflicts_marker_length=$marker_length",
  "-c", "JJDiffConflicts!", "$output", "$base", "$left", "$right",
]
merge-tool-edits-conflict-markers = true

[ui]
diff-editor = ["nvim", "-c", "DiffEditor $left $right $output"]
editor = "nvim"
# Let the syntax-aware resolver handle straightforward conflicts first. If it
# leaves conflicts behind, resolve them interactively with `--tool vimdiff`.
merge-tool = "mergiraf"
default-command = "log"
